doctrine_mongodb:
  connections:
    default:
      server: "%env(resolve:MONGODB_URL)%"
      options:
        username: arcadiauser
        password: raqN3N7f8PO91Xt5
        authMechanism: "SCRAM-SHA-1"
        authSource: "admin"
        retryWrites: true
        tls: true
        ssl: true
  default_database: "%env(MONGODB_DB)%"
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          type: attribute
          dir: "%kernel.project_dir%/src/Document"
          prefix: 'App\Document'
          alias: App

when@prod:
  doctrine_mongodb:
    auto_generate_proxy_classes: false
    auto_generate_hydrator_classes: false
    document_managers:
      default:
        metadata_cache_driver:
          type: service
          id: doctrine_mongodb.system_cache_pool

  framework:
    cache:
      pools:
        doctrine_mongodb.system_cache_pool:
          adapter: cache.system
