database:
  type: mysql:11.0
  disk: 1024
  configuration:
    schemas:
      - arcadia
    endpoints:
      mysql:
        default_schema: arcadia
        privileges:
          arcadia: admin

mongodb:
  type: mongodb-enterprise:7.0
  disk: 512
  configuration:
    database:
      - arcadia
